controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    aubo_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


aubo_joint_trajectory_controller:
  ros__parameters:
    joints:
      - aubo_shoulder_joint
      - aubo_upperArm_joint
      - aubo_foreArm_joint
      - aubo_wrist1_joint
      - aubo_wrist2_joint
      - aubo_wrist3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
